### PR TITLE
UPDATE: cft/developer-tools version

### PR DESCRIPTION
**Pull request by apeabody**
Update cft/developer-tools to version 1.3 for linter.

### CODE REVIEW

**Comment by apeabody** [comment]
@bharathkkb Should we bump the version for testing? https://github.com/terraform-google-modules/cloud-foundation-training/blob/7cc6ae014aa31aaa68efafede84c557b851c214d/build/int.cloudbuild.yaml#L104

**Comment by bharathkkb** [comment]
@apeabody yes and lets also bump https://github.com/terraform-google-modules/cloud-foundation-training/blob/7cc6ae014aa31aaa68efafede84c557b851c214d/Makefile#L21

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_headers
 All files need a license header. Please make sure all your files include the appropriate header. A helper tool available [here](https://github.com/google/addlicense). 
 ```bash 
Checking file headers
./test/integration/05-Load-Balancer/inspec.yml
./test/integration/01-Getting-Started/inspec.yml
./test/integration/04-Instance-Group/inspec.yml
./.github/workflows/stale.yml
./test/integration/02-IAM/inspec.yml
./test/integration/03-Networking/inspec.yml
./test/integration/06-Cloud-Function/inspec.yml
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate ./01-Getting-Started
Success!
 The configuration is valid.
terraform_validate ./02-IAM
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "project_iam_bindings" (declared at main.tf line 42) has invalid
│
 
source address "": invalid source string: .
╵
terraform_validate ./03-Networking
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "cloud_nat" (declared at main.tf line 55) has invalid source address
│
 
"": invalid source string: .
╵
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "network" (declared at main.tf line 38) has invalid source address
│
 
"": invalid source string: .
╵
terraform_validate ./04-Instance-Group
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "instance_template" (declared at main.tf line 63) has invalid source
│
 
address "": invalid source string: .
╵
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "managed_instance_group" (declared at main.tf line 83) has invalid
│
 
source address "": invalid source string: .
╵
terraform_validate ./05-Load-Balancer
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "load_balancer" (declared at main.tf line 76) has invalid source
│
 
address "": invalid source string: .
╵
terraform_validate ./06-Cloud-Function
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "image_processing_function" (declared at main.tf line 53) has
│
 
invalid source address "": invalid source string: .
╵
terraform_validate ./other/terraform-codelab/lab-app
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on provider.tf line 18, in provider "google":
│
 
  18:   version     = 
"~> 2.5"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
╷
│
 
Error: 
Invalid function argument
│
 
│
 
  on provider.tf line 20, in provider "google":
│
 
  20:   credentials = file("
credentials.json
")
│
 
│
 
Invalid value for "path" parameter: no file exists at "credentials.json";
│
 
this function works only with files that are distributed as part of the
│
 
configuration source code, so if this file will be created by a resource in
│
 
this configuration you must instead obtain this result from an attribute of
│
 
that resource.
╵
terraform_validate ./other/terraform-codelab/lab-networking
╷
│
 
Error: 
Invalid function argument
│
 
│
 
  on provider.tf line 19, in provider "google":
│
 
  19:   credentials = file("
credentials.json
")
│
 
│
 
Invalid value for "path" parameter: no file exists at "credentials.json";
│
 
this function works only with files that are distributed as part of the
│
 
configuration source code, so if this file will be created by a resource in
│
 
this configuration you must instead obtain this result from an attribute of
│
 
that resource.
╵
terraform_validate ./test/fixtures/01-Getting-Started
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on versions.tf line 18, in provider "google":
│
 
  18:   version = 
"3.53"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on example.tf line 19, in module "example":
│
 
  19:   
project_id
 = var.project_id
│
 
│
 
An argument named "project_id" is not expected here.
╵
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on example.tf line 20, in module "example":
│
 
  20:   
region
     = "us-central1"
│
 
│
 
An argument named "region" is not expected here.
╵
terraform_validate ./test/fixtures/02-IAM
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "project_iam_bindings" (declared at ../../../02-IAM/main.tf line 42)
│
 
has invalid source address "": invalid source string: .
╵
terraform_validate ./test/fixtures/03-Networking
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "cloud_nat" (declared at ../../../03-Networking/main.tf line 55) has
│
 
invalid source address "": invalid source string: .
╵
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "network" (declared at ../../../03-Networking/main.tf line 38) has
│
 
invalid source address "": invalid source string: .
╵
terraform_validate ./test/fixtures/04-Instance-Group
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "instance_template" (declared at ../../../04-Instance-Group/main.tf
│
 
line 63) has invalid source address "": invalid source string: .
╵
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "managed_instance_group" (declared at
│
 
../../../04-Instance-Group/main.tf line 83) has invalid source address "":
│
 
invalid source string: .
╵
terraform_validate ./test/fixtures/05-Load-Balancer
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "load_balancer" (declared at ../../../05-Load-Balancer/main.tf line
│
 
76) has invalid source address "": invalid source string: .
╵
terraform_validate ./test/fixtures/06-Cloud-Function
╷
│
 
Error: 
Invalid module source address
│
 
│
 
Module "image_processing_function" (declared at
│
 
../../../06-Cloud-Function/main.tf line 53) has invalid source address "":
│
 
invalid source string: .
╵
terraform_validate ./test/setup
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on versions.tf line 22, in provider "google":
│
 
  22:   version = 
"~> 3.41"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
 ```

**Comment by apeabody** [comment]
Will include in https://github.com/terraform-google-modules/cloud-foundation-training/pull/48

**Pull request closed without merging**
