### PR TITLE
add in terraform-codelab source

### PR DESCRIPTION
**Pull request by dylanmpeck**
To solve this [issue](https://github.com/terraform-google-modules/cloud-foundation-training/issues/44).

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_python
 Failed flake8 Python lint check. 
 ```bash 
Running flake8
./06-Cloud-Function/function_source/main.py:39:58: E999 SyntaxError: invalid syntax
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate ./01-Getting-Started 
Success!
 The configuration is valid.
terraform_validate ./02-IAM 
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Warning: 
Version constraints inside provider configuration blocks are deprecated
  on main.tf line 20, in provider "google":
  20:   version = 
"~> 3.53"
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.
Error: 
Missing required argument
  on main.tf line 42, in module "project_iam_bindings":
  42: module "project_iam_bindings" 
{
The argument "source" is required, but no definition was found.
terraform_validate ./03-Networking 
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Warning: 
Version constraints inside provider configuration blocks are deprecated
  on main.tf line 20, in provider "google":
  20:   version = 
"~> 3.53"
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.
Error: 
Missing required argument
  on main.tf line 38, in module "network":
  38: module "network" 
{
The argument "source" is required, but no definition was found.
Error: 
Missing required argument
  on main.tf line 55, in module "cloud_nat":
  55: module "cloud_nat" 
{
The argument "source" is required, but no definition was found.
terraform_validate ./04-Instance-Group 
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Warning: 
Version constraints inside provider configuration blocks are deprecated
  on main.tf line 20, in provider "google":
  20:   version = 
"~> 3.53"
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.
Error: 
Invalid resource type name
  on main.tf line 42, in resource "" "service_account_user":
  42: resource 
""
 "service_account_user" {
A name must start with a letter or underscore and may contain only letters,
digits, underscores, and dashes.
Error: 
Missing required argument
  on main.tf line 63, in module "instance_template":
  63: module "instance_template" 
{
The argument "source" is required, but no definition was found.
Error: 
Missing required argument
  on main.tf line 83, in module "managed_instance_group":
  83: module "managed_instance_group" 
{
The argument "source" is required, but no definition was found.
terraform_validate ./05-Load-Balancer 
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Warning: 
Version constraints inside provider configuration blocks are deprecated
  on main.tf line 20, in provider "google":
  20:   version = 
"~> 3.53"
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.
Error: 
Missing required argument
  on main.tf line 76, in module "load_balancer":
  76: module "load_balancer" 
{
The argument "source" is required, but no definition was found.
terraform_validate ./06-Cloud-Function 
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Warning: 
Version constraints inside provider configuration blocks are deprecated
  on main.tf line 20, in provider "google":
  20:   version = 
"~> 3.53"
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.
Error: 
Missing required argument
  on main.tf line 53, in module "image_processing_function":
  53: module "image_processing_function" 
{
The argument "source" is required, but no definition was found.
terraform_validate ./other/terraform-codelab/lab-app 
Warning: 
Version constraints inside provider configuration blocks are deprecated
  on provider.tf line 18, in provider "google":
  18:   version     = 
"~> 2.5"
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.
Error: 
Invalid function argument
  on provider.tf line 20, in provider "google":
  20:   credentials = file("
credentials.json
")
Invalid value for "path" parameter: no file exists at credentials.json; this
function works only with files that are distributed as part of the
configuration source code, so if this file will be created by a resource in
this configuration you must instead obtain this result from an attribute of
that resource.
terraform_validate ./other/terraform-codelab/lab-networking 
Error: 
Invalid function argument
  on provider.tf line 19, in provider "google":
  19:   credentials = file("
credentials.json
")
Invalid value for "path" parameter: no file exists at credentials.json; this
function works only with files that are distributed as part of the
configuration source code, so if this file will be created by a resource in
this configuration you must instead obtain this result from an attribute of
that resource.
terraform_validate ./test/fixtures/01-Getting-Started 
Warning: 
Version constraints inside provider configuration blocks are deprecated
  on versions.tf line 18, in provider "google":
  18:   version = 
"3.53"
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.
(and one more similar warning elsewhere)
Error: 
Unsupported argument
  on example.tf line 19, in module "example":
  19:   
project_id
 = var.project_id
An argument named "project_id" is not expected here.
Error: 
Unsupported argument
  on example.tf line 20, in module "example":
  20:   
region
     = "us-central1"
An argument named "region" is not expected here.
terraform_validate ./test/fixtures/02-IAM 
Error: 
Failed to download module
Could not download module "project_iam_bindings" (../../../02-IAM/main.tf:42)
source code from "": invalid source string: 
Error: 
Failed to download module
Could not download module "project_iam_bindings" (../../../02-IAM/main.tf:42)
source code from "": invalid source string: 
terraform_validate ./test/fixtures/03-Networking 
Error: 
Failed to download module
Could not download module "cloud_nat" (../../../03-Networking/main.tf:55)
source code from "": invalid source string: 
Error: 
Failed to download module
Could not download module "network" (../../../03-Networking/main.tf:38) source
code from "": invalid source string: 
Error: 
Failed to download module
Could not download module "cloud_nat" (../../../03-Networking/main.tf:55)
source code from "": invalid source string: 
Error: 
Failed to download module
Could not download module "cloud_nat" (../../../03-Networking/main.tf:55)
source code from "": invalid source string: 
Error: 
Failed to download module
Could not download module "network" (../../../03-Networking/main.tf:38) source
code from "": invalid source string: 
Error: 
Failed to download module
Could not download module "cloud_nat" (../../../03-Networking/main.tf:55)
source code from "": invalid source string: 
Error: 
Failed to download module
Could not download module "network" (../../../03-Networking/main.tf:38) source
code from "": invalid source string: 
Error: 
Failed to download module
Could not download module "cloud_nat" (../../../03-Networking/main.tf:55)
source code from "": invalid source string: 
Error: 
Failed to download module
Could not download module "network" (../../../03-Networking/main.tf:38) source
code from "": invalid source string: 
terraform_validate ./test/fixtures/04-Instance-Group 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "managed_instance_group"
(../../../04-Instance-Group/main.tf:83) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "managed_instance_group"
(../../../04-Instance-Group/main.tf:83) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "managed_instance_group"
(../../../04-Instance-Group/main.tf:83) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "managed_instance_group"
(../../../04-Instance-Group/main.tf:83) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "managed_instance_group"
(../../../04-Instance-Group/main.tf:83) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "managed_instance_group"
(../../../04-Instance-Group/main.tf:83) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "managed_instance_group"
(../../../04-Instance-Group/main.tf:83) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "managed_instance_group"
(../../../04-Instance-Group/main.tf:83) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "instance_template"
(../../../04-Instance-Group/main.tf:63) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "managed_instance_group"
(../../../04-Instance-Group/main.tf:83) source code from "": invalid source
string: 
terraform_validate ./test/fixtures/05-Load-Balancer 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "load_balancer"
(../../../05-Load-Balancer/main.tf:76) source code from "": invalid source
string: 
terraform_validate ./test/fixtures/06-Cloud-Function 
Error: 
Failed to download module
Could not download module "image_processing_function"
(../../../06-Cloud-Function/main.tf:53) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "image_processing_function"
(../../../06-Cloud-Function/main.tf:53) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "image_processing_function"
(../../../06-Cloud-Function/main.tf:53) source code from "": invalid source
string: 
Error: 
Failed to download module
Could not download module "image_processing_function"
(../../../06-Cloud-Function/main.tf:53) source code from "": invalid source
string: 
terraform_validate ./test/setup 
Warning: 
Version constraints inside provider configuration blocks are deprecated
  on versions.tf line 22, in provider "google":
  22:   version = 
"~> 3.41"
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.
(and one more similar warning elsewhere)
Success!
 The configuration is valid, but there were some validation warnings as shown above.
 ```

**Comment by morgante** [comment]
@dylanmpeck Do you mind formatting the content to fix the linter errors?

**Comment by dylanmpeck** [comment]
@morgante I believe I fixed the linter errors with the material I'm adding, but now it seems to be getting hung up on source that already existed in the repo. I don't think any of the files pointed to in the error message are affected by my PR.

Am I making a mistake or missing something?

**Review by bharathkkb — COMMENTED** [review]
@dylanmpeck Most of those are safe to ignore (the bot does not do swap with solutions). 

One error I did notice is 
```
terraform_validate ./other/terraform-codelab/lab-app 

Warning: Version constraints inside provider configuration blocks are deprecated

  on provider.tf line 18, in provider "google":
  18:   version     = "~> 2.5"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider

version constraint into the required_providers block.

Error: Invalid function argument

  on provider.tf line 20, in provider "google":
  20:   credentials = file("credentials.json")

Invalid value for "path" parameter: no file exists at credentials.json; this
function works only with files that are distributed as part of the
configuration source code, so if this file will be created by a resource in
this configuration you must instead obtain this result from an attribute of
that resource.
```

**Comment by dylanmpeck** [comment]
Thanks, Bharath. I silenced the provider warning.

But, for the other error, the service account and "credentials.json" file is created during the beginning of the lab. The user is walked through the process. So, it's not causing problem in the context of the lab, but it could potentially be an issue if this code is being used for other purposes.

Should this lab be using a different authentication method?

**Comment by morgante** [comment]
Ideally the lab should not use downloaded service account keys, but I think this is fine for now.

**Review by morgante — APPROVED** [review]

**Comment by dylanmpeck** [comment]
Thank you! The Qwiklab is updated to use this repo now.

**Pull request merged**
